<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Dashboard</name>
   <tag></tag>
   <elementGuidId>c95d797a-fc5f-435e-97a9-976d9e89c5d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.woocommerce-MyAccount-navigation-link.woocommerce-MyAccount-navigation-link--dashboard</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-55']/div/div/nav/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>e1335771-3761-4d0f-8739-61b1d886e569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-MyAccount-navigation-link woocommerce-MyAccount-navigation-link--dashboard</value>
      <webElementGuid>612a147f-b488-433b-991d-68f7af9ceb01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				Dashboard
			</value>
      <webElementGuid>07f05325-978f-45fa-8718-39070aafc17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-55&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/nav[@class=&quot;woocommerce-MyAccount-navigation&quot;]/ul[1]/li[@class=&quot;woocommerce-MyAccount-navigation-link woocommerce-MyAccount-navigation-link--dashboard&quot;]</value>
      <webElementGuid>691526e6-4a3c-43cf-a0b7-27a7bdc29720</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-55']/div/div/nav/ul/li</value>
      <webElementGuid>3935458e-bd98-4e21-bdff-b84051b819c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='planteazoom'])[1]/following::li[1]</value>
      <webElementGuid>ed63e5fa-e303-4a63-9026-f52ede305f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::li[1]</value>
      <webElementGuid>11bd5092-5c97-4f96-8095-1c45c1f22011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Orders'])[1]/preceding::li[1]</value>
      <webElementGuid>df5f6cf2-6755-4bda-878e-4a5b787ed012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/div/nav/ul/li</value>
      <webElementGuid>5bf80096-3532-4806-8d17-16a97252f05a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '
				Dashboard
			' or . = '
				Dashboard
			')]</value>
      <webElementGuid>f1477808-cbff-4615-bdf5-96775e8135c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
