<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Logout</name>
   <tag></tag>
   <elementGuidId>f89326c1-284c-4b1a-b51c-6ba7448ba032</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.woocommerce-MyAccount-navigation-link.woocommerce-MyAccount-navigation-link--customer-logout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-55']/div/div/nav/ul/li[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>9f15ebed-6b6a-4afa-9cea-28f54ec5455a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>woocommerce-MyAccount-navigation-link woocommerce-MyAccount-navigation-link--customer-logout</value>
      <webElementGuid>64a94504-df03-41f0-872e-8eac57ad27eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				Logout
			</value>
      <webElementGuid>a49637c7-0cee-4e2c-bbd6-29ef0f972d26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-55&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/nav[@class=&quot;woocommerce-MyAccount-navigation&quot;]/ul[1]/li[@class=&quot;woocommerce-MyAccount-navigation-link woocommerce-MyAccount-navigation-link--customer-logout&quot;]</value>
      <webElementGuid>6eb53a1d-05f2-4252-a956-3118feaaff46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-55']/div/div/nav/ul/li[7]</value>
      <webElementGuid>471e3620-ff85-4547-b261-b8369671e911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account details'])[1]/following::li[1]</value>
      <webElementGuid>f30e087d-5994-42f4-80e6-3dc5c603ee7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment methods'])[1]/following::li[2]</value>
      <webElementGuid>2dba1d0b-52b0-4fa9-91fe-2514a5c5e365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Log out'])[1]/preceding::li[1]</value>
      <webElementGuid>6a7db4e0-2f03-4b1f-b16c-99999083c109</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]</value>
      <webElementGuid>fe2ec4b1-eeec-4212-ac97-091f340bafa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = '
				Logout
			' or . = '
				Logout
			')]</value>
      <webElementGuid>6083c6ee-48f4-4faf-80bb-5b311757b202</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
