<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Undo</name>
   <tag></tag>
   <elementGuidId>cdea87d1-1d53-4de3-8c07-6e8051a6fa7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.restore-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-53']/div/div/div/div/p/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7b961d02-2fc2-44e7-be8b-288612a313d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://kotakoki.wijaysali.my.id/cart-2/?undo_item=70efdf2ec9b086079795c442636b55fb&amp;_wpnonce=afc0b14a03</value>
      <webElementGuid>26f7a4bf-bc0c-4f2a-8b01-919fb36890c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>restore-item</value>
      <webElementGuid>39de7299-d170-4035-95af-a336f7856306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Undo?</value>
      <webElementGuid>dce187e7-8725-4e30-aec8-1e019c3f2bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-53&quot;)/div[@class=&quot;entry-content&quot;]/div[@class=&quot;woocommerce&quot;]/div[@class=&quot;woocommerce-notices-wrapper&quot;]/div[@class=&quot;woocommerce-message&quot;]/p[@class=&quot;with-button&quot;]/a[@class=&quot;restore-item&quot;]</value>
      <webElementGuid>78dbb9d2-dae5-439d-a69e-537132355e6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-53']/div/div/div/div/p/a</value>
      <webElementGuid>2185a0be-8c3d-460f-932f-76bc941e9405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Undo?')]</value>
      <webElementGuid>2fe7ce95-f7dd-4e46-a1ee-ba7a9b3e35e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart'])[1]/following::a[1]</value>
      <webElementGuid>cc4fb072-e25d-429c-8b59-34730e0b8eb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::a[1]</value>
      <webElementGuid>b52b3bf3-ba85-46c4-8449-7e0da8fd7efb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You might like these'])[1]/preceding::a[1]</value>
      <webElementGuid>127a80d5-4d36-4572-8373-189848b98380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New!'])[1]/preceding::a[1]</value>
      <webElementGuid>523dde66-54ab-4b98-a741-37a8fa094f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Undo?']/parent::*</value>
      <webElementGuid>5a120145-6744-48ac-8a3f-d359291d6f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://kotakoki.wijaysali.my.id/cart-2/?undo_item=70efdf2ec9b086079795c442636b55fb&amp;_wpnonce=afc0b14a03')]</value>
      <webElementGuid>db80f6b2-b753-4c34-9aa0-3bce11d24172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/a</value>
      <webElementGuid>2930754f-334b-48cb-89ca-1331c30204c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://kotakoki.wijaysali.my.id/cart-2/?undo_item=70efdf2ec9b086079795c442636b55fb&amp;_wpnonce=afc0b14a03' and (text() = 'Undo?' or . = 'Undo?')]</value>
      <webElementGuid>61e15b95-4dc8-43da-9c99-cd5a7f9408fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
