<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Address 2</name>
   <tag></tag>
   <elementGuidId>de722cef-0010-4cb0-b7bd-acd84ef31376</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_address_2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_address_2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3aba0ceb-14a5-410b-9100-068321a3ac4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>06c70efc-580d-4c9b-91d6-8412ea4e88eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>a8fd020c-62ca-4aba-b9fe-9f6feedbeb38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_address_2</value>
      <webElementGuid>d1ce1286-cfd3-4e7a-8a95-81c94cfad79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_address_2</value>
      <webElementGuid>784751d9-c2ce-442f-b083-aab5a0326964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Apartment, suite, unit, etc. (optional)</value>
      <webElementGuid>c8b80069-b2d9-49b4-b9cf-675402c84502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>address-line2</value>
      <webElementGuid>5497e742-852e-41b2-86f2-226434dc6ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-placeholder</name>
      <type>Main</type>
      <value>Apartment, suite, unit, etc. (optional)</value>
      <webElementGuid>74b5b0bb-dcc8-479f-ad97-68746888e04d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_address_2&quot;)</value>
      <webElementGuid>a763e1f7-ea5d-49b4-86e1-ed313d925ef7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_address_2']</value>
      <webElementGuid>c2e73676-5d03-4d3d-aab1-18b264b60fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_address_2_field']/span/input</value>
      <webElementGuid>03c4e635-fbd2-4d3d-9984-7f4f9ed0aae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[6]/span/input</value>
      <webElementGuid>ced91d78-5fc6-4557-a74f-40975fa72eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_address_2' and @id = 'billing_address_2' and @placeholder = 'Apartment, suite, unit, etc. (optional)']</value>
      <webElementGuid>6871d948-494d-4102-9c81-a8d274a74c30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
