<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_Last Name</name>
   <tag></tag>
   <elementGuidId>9992510d-0cd5-4c6c-91b1-75daaa6e3626</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#billing_last_name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing_last_name']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c44575c-3db2-45d2-a45a-d37337be2f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0e01c935-32c6-473f-8d12-158787ccfa9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text </value>
      <webElementGuid>9652ae81-e74f-481e-8631-810a2e23ad25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing_last_name</value>
      <webElementGuid>409b876c-6826-4b5b-8b32-47219f7125f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing_last_name</value>
      <webElementGuid>36bedfcc-8f08-4610-88fa-91e9f4a50081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>family-name</value>
      <webElementGuid>2959ecd7-341e-49c6-914c-5c41e59da499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing_last_name&quot;)</value>
      <webElementGuid>cc07aca6-4378-4976-94a2-f2b3a2b0c158</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing_last_name']</value>
      <webElementGuid>78f482ac-3e7f-4d65-8c09-17f3d6be9341</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//p[@id='billing_last_name_field']/span/input</value>
      <webElementGuid>f0791f71-b895-4d26-b9a3-5f450095fa5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/span/input</value>
      <webElementGuid>4929db49-8c82-4fe6-905b-f47001d00129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'billing_last_name' and @id = 'billing_last_name']</value>
      <webElementGuid>a1a7c142-b519-48ed-b9fe-4eb516853896</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
