<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pgr_3</name>
   <tag></tag>
   <elementGuidId>477f7b89-bbf9-4457-9ac3-b3895ec0a7f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-247']/div/p[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>2a8c9491-8832-4575-9d64-9b29e8c741cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>has-medium-font-size</value>
      <webElementGuid>74d6a300-c32f-4be6-b35d-edb3d061804f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>For the love of finding the best spices and cooking, we aim to introduce Indonesia’s wonderful cuisine to our friends around the world. We are working directly with Indonesian farmers, carefully select the spices, prepare them, pack them and deliver them to your door. </value>
      <webElementGuid>cdc6df32-ca53-467f-90a3-c9eb709488b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-247&quot;)/div[@class=&quot;entry-content&quot;]/p[@class=&quot;has-medium-font-size&quot;]</value>
      <webElementGuid>63355e58-fdc5-44ce-9f96-822e19d458b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-247']/div/p[3]</value>
      <webElementGuid>71cfb03d-7691-403e-b09e-33e83fda9a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='chef'])[1]/following::p[1]</value>
      <webElementGuid>99f5e11c-c65b-45d0-9582-759666aa6adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='box'])[1]/following::p[1]</value>
      <webElementGuid>17d64778-0e87-4262-a9c2-8b8ade8366b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Newsletter'])[1]/preceding::p[4]</value>
      <webElementGuid>02cc6b47-9056-432e-9e0c-478f80ba31d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[3]</value>
      <webElementGuid>7861e59b-22c1-46fb-ad96-ae13166b1e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'For the love of finding the best spices and cooking, we aim to introduce Indonesia’s wonderful cuisine to our friends around the world. We are working directly with Indonesian farmers, carefully select the spices, prepare them, pack them and deliver them to your door. ' or . = 'For the love of finding the best spices and cooking, we aim to introduce Indonesia’s wonderful cuisine to our friends around the world. We are working directly with Indonesian farmers, carefully select the spices, prepare them, pack them and deliver them to your door. ')]</value>
      <webElementGuid>a97e0c01-da53-4abc-ad2f-d383e233a28b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
