<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pgr_2</name>
   <tag></tag>
   <elementGuidId>f14fbef7-22f8-445a-84a3-10884c3383a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-247']/div/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>a5723371-17b8-4cab-ae40-073a0eae230a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>has-medium-font-size</value>
      <webElementGuid>1e5fa033-a6af-48e9-b027-273d9fe50697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>In Indonesian language, “kotak” means box and “koki” means chef. With Kotakoki or “Chef Box”, anyone with a passion for Indonesian culinary can be a chef of authentic Indonesian foods.</value>
      <webElementGuid>db5d8622-0dd5-4392-ac0b-6acca7a79404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-247&quot;)/div[@class=&quot;entry-content&quot;]/p[@class=&quot;has-medium-font-size&quot;]</value>
      <webElementGuid>29265061-337c-4493-a8d9-adca3542d0d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-247']/div/p[2]</value>
      <webElementGuid>62df2676-6905-402a-916e-b0949dbc44c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ENG'])[1]/following::p[2]</value>
      <webElementGuid>38ec534d-d687-4db2-9d21-ebac4994d814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::p[2]</value>
      <webElementGuid>441a3fec-172e-4cb4-ae54-ab424913feee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]</value>
      <webElementGuid>83ea7c8e-6994-4c56-8596-1fad80eac50b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'In Indonesian language, “kotak” means box and “koki” means chef. With Kotakoki or “Chef Box”, anyone with a passion for Indonesian culinary can be a chef of authentic Indonesian foods.' or . = 'In Indonesian language, “kotak” means box and “koki” means chef. With Kotakoki or “Chef Box”, anyone with a passion for Indonesian culinary can be a chef of authentic Indonesian foods.')]</value>
      <webElementGuid>524d475c-b541-4606-8730-76c6306f5de6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
