<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pgr_4</name>
   <tag></tag>
   <elementGuidId>53368425-58e6-470d-bf29-e12da767fec5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//article[@id='post-247']/div/p[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9e63c40c-906b-4f57-a3e4-8a732ff297f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>has-medium-font-size</value>
      <webElementGuid>ecb0eed2-a966-43f7-ac49-59b09af9d515</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Indonesia’s multifaceted cuisine is heavily influenced by the Indian, Arabian, and Chinese traders that came to Indonesia long ago, bringing their essential ingredients with them. But, there are a few spices grown and found in Indonesia, considered as exotic to expats yet comforting to Indonesians.</value>
      <webElementGuid>3f04b92d-b17e-4d6a-9207-b9b651130082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;post-247&quot;)/div[@class=&quot;entry-content&quot;]/p[@class=&quot;has-medium-font-size&quot;]</value>
      <webElementGuid>115c2550-5cc9-4238-9bf3-36f01673e24f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='post-247']/div/p[4]</value>
      <webElementGuid>f1f705a8-a108-48d7-9c81-092add1a9aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='chef'])[1]/following::p[2]</value>
      <webElementGuid>9d13bacd-4d45-4acc-a0fd-f686fd3686bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='box'])[1]/following::p[2]</value>
      <webElementGuid>52cc95ce-c58d-46d1-8402-98801c48edcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Newsletter'])[1]/preceding::p[3]</value>
      <webElementGuid>bc55aeb3-8b12-44c2-836b-2730f849f83d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Indonesia’s multifaceted cuisine is heavily influenced by the Indian, Arabian, and Chinese traders that came to Indonesia long ago, bringing their essential ingredients with them. But, there are a few spices grown and found in Indonesia, considered as exotic to expats yet comforting to Indonesians.']/parent::*</value>
      <webElementGuid>583d181f-0dd1-4f5f-95b5-e099ee4d6f06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[4]</value>
      <webElementGuid>d27b7149-3fb0-430c-a9cf-b4ab11200309</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Indonesia’s multifaceted cuisine is heavily influenced by the Indian, Arabian, and Chinese traders that came to Indonesia long ago, bringing their essential ingredients with them. But, there are a few spices grown and found in Indonesia, considered as exotic to expats yet comforting to Indonesians.' or . = 'Indonesia’s multifaceted cuisine is heavily influenced by the Indian, Arabian, and Chinese traders that came to Indonesia long ago, bringing their essential ingredients with them. But, there are a few spices grown and found in Indonesia, considered as exotic to expats yet comforting to Indonesians.')]</value>
      <webElementGuid>fdfe4705-7a37-4069-b7e7-f67116d5a120</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
